### ISSUE TITLE
per site like firefox

### ISSUE THREAD

**Issue by cubakcabak** [192000/nukem#1]
firefox has options to "forget this site" when right clicking a link from history, and it's clean all of site data from that site domain only.

please make an option so that when we click the icon it clears out data from the current site opened in current tab, but keep others site untouched.

thank you for your wonderful extensions.

**Comment by tre-x** [comment]
Thank you for the suggestion! I will consider this feature for version 4.

**Comment by tre-x** [comment]
**Just added that feature in version 4**, which is now available on the webstore. Thank you for the suggestion, I am always looking for feedback/suggestions for Nuke'm.
